modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="creeperphantom"
version="${version}"
displayName="Creeper Phantom"
description='''Explosive phantom and enderman variants with charged forms, configurable natural spawns, autonomous inventory raids and optional GT multiblock targeting.'''

[[dependencies.creeperphantom]]
modId="forge"
mandatory=true
versionRange="[47.3.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.creeperphantom]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
