modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="creeperphantom"
version="${version}"
displayName="Creeper Phantom"
description='''A phantom with a creeper's face and explosive temperament. Stalks sleepless players and occasionally raids exposed inventories.'''

[[dependencies.creeperphantom]]
modId="forge"
mandatory=true
versionRange="[47.3.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.creeperphantom]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
